### ISSUE TITLE
Tillable results

### ISSUE THREAD

**Issue by chicogamedev** [usysrc/iga#2]
Hi,

It's an awesome port and gives me a lot of inspiration but I have one question : 

I've heard that the original WFC was capable of returning tillable results.

I've made some test with IGA and it nearly nails it but that still a matter of chance.

Do you know if it would be possible to make an input parameter to ask for tillable result ?

Thanks, keep up the great work. This algorithm is amazing.

**Comment by usysrc** [comment]
Hey Chico, what do you mean by tillable? Do you have a concrete example in implementations of WFC?

**Comment by chicogamedev** [comment]
Actually not. I heard probably something wrong. Sorry for the noise.

But it could be an amazing feature 🚀 

By tillable I meant "that repeats well together" (tilemap).
