### ISSUE TITLE
Empty colors in output & strange behavior

### ISSUE THREAD

**Issue by chicogamedev** [usysrc/iga#3]
Hello,

It happens that the output contains empty colors (value 0). It look like the output is filled with holes.

Can you explain why and may be help me correcting the issue ?

Also I do not understand the reset to nil of all the globals and principally "colours" at line 490 in function "iga:generate()".
It clears all the vars and I am forced to comment this code to be able to get the output with "iga:getColours()".

Am I missing something ?

Thanks

**Comment by usysrc** [comment]
This is built upon hempulis implementaiton. I can not explain the black/transparent colors at this time either. You are welcome to submit a PR if you find out more.
